@file:OptIn(kotlin.time.ExperimentalTime::class)

package com.novarytm.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.material.icons.filled.Person
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.draw.drawWithContent
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.drawscope.Stroke
import com.novarytm.tracker.CycleTracker
import kotlin.time.Clock
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.novarytm.db.CycleEntry
import com.novarytm.sync.PartnerPermissions
import kotlinx.datetime.*
import kotlinx.coroutines.launch

data class UiYearMonth(val year: Int, val monthNumber: Int) {
    fun lengthOfMonth(): Int = when (monthNumber) {
        2 -> if (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) 29 else 28
        4, 6, 9, 11 -> 30
        else -> 31
    }
        
    @Suppress("DEPRECATION")
    fun atDay(day: Int): LocalDate = LocalDate(year, monthNumber, day)

    companion object {
        fun now(): UiYearMonth {
            val date = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault()).date
            return UiYearMonth(date.year, date.month.number)
        }
    }
}

@Composable
fun CalendarHeader(
    currentMonth: UiYearMonth,
    onPrevMonth: () -> Unit,
    onNextMonth: () -> Unit
) {
    val monthName = when (currentMonth.monthNumber) {
        1 -> "January"
        2 -> "February"
        3 -> "March"
        4 -> "April"
        5 -> "May"
        6 -> "June"
        7 -> "July"
        8 -> "August"
        9 -> "September"
        10 -> "October"
        11 -> "November"
        12 -> "December"
        else -> ""
    }

    Row(
        modifier = Modifier.fillMaxWidth().padding(16.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        IconButton(onClick = onPrevMonth) {
            Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Previous Month")
        }

        Text(
            text = "$monthName ${currentMonth.year}",
            style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold)
        )

        IconButton(onClick = onNextMonth) {
            Icon(Icons.AutoMirrored.Filled.ArrowForward, contentDescription = "Next Month")
        }
    }
}

@Composable
fun CalendarGrid(
    currentMonth: UiYearMonth,
    loggedDates: Set<LocalDate>,    // Dates pulled from your DB history
    predictedDates: Set<LocalDate>, // Dates generated by the Rust Core
    fertileDates: Set<LocalDate>,    // Dates generated by the Rust Core
    sexualActivityDates: Map<LocalDate, String> = emptyMap(),
    selectedDate: LocalDate?,
    onDateSelected: (LocalDate) -> Unit
) {
    val daysToRender = remember(currentMonth) {
        val firstDay = currentMonth.atDay(1)
        val startOffset = firstDay.dayOfWeek.isoDayNumber % 7 
        val lengthOfMonth = currentMonth.lengthOfMonth()
        
        val emptySlots = List(startOffset) { null }
        val actualDays = (1..lengthOfMonth).toList()
        
        emptySlots + actualDays
    }

    // Bounding the grid with exact rows and columns prevents cropping on all screen sizes
    Column(
        modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp)
    ) {
        val rows = daysToRender.chunked(7)
        rows.forEach { rowDays ->
            Row(modifier = Modifier.fillMaxWidth()) {
                rowDays.forEach { day ->
                    Box(
                        modifier = Modifier
                            .weight(1f)
                            .height(44.dp)
                            .padding(2.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        if (day != null) {
                            val currentDate = currentMonth.atDay(day)
                            
                            val isLogged = loggedDates.contains(currentDate)
                            val isPredicted = predictedDates.contains(currentDate)
                            val isFertile = fertileDates.contains(currentDate)
                            val isToday = currentDate == Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault()).date
                            val isSexual = sexualActivityDates.containsKey(currentDate)
                            val sexualType = sexualActivityDates[currentDate]?.lowercase()
                            
                            val appColors = LocalAppColors.current
                            val PeriodColor = appColors.primaryVariant
                            val FertileColor = appColors.secondaryVariant
                            val TodayColor = appColors.todayHighlight

                            Box(
                                modifier = Modifier
                                    .size(38.dp)
                                    .clickable { onDateSelected(currentDate) }
                                    .then(
                                        if (selectedDate == currentDate) {
                                            Modifier.border(2.dp, Color.Black, CircleShape)
                                        } else Modifier
                                    )
                                    .then(
                                        when {
                                            isLogged -> Modifier.background(PeriodColor, CircleShape)
                                            isFertile -> Modifier.background(FertileColor, CircleShape)
                                            isPredicted -> Modifier.drawBehind {
                                                drawCircle(
                                                    color = PeriodColor,
                                                    style = Stroke(
                                                        width = 1.5.dp.toPx(),
                                                        pathEffect = PathEffect.dashPathEffect(
                                                            intervals = floatArrayOf(8f, 8f), 
                                                            phase = 0f
                                                        )
                                                    )
                                                )
                                            }
                                            else -> Modifier
                                        }
                                    ),
                                contentAlignment = Alignment.Center
                            ) {
                                Text(
                                    text = day.toString(),
                                    color = if (isLogged) Color.White else if (isToday) TodayColor else MaterialTheme.colorScheme.onSurface,
                                    style = MaterialTheme.typography.bodyMedium.copy(fontWeight = if (isToday || isLogged) FontWeight.Bold else FontWeight.Normal)
                                )
                                
                                Row(
                                    modifier = Modifier.align(Alignment.BottomCenter).padding(bottom = 2.dp),
                                    horizontalArrangement = Arrangement.spacedBy(2.dp),
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    if (isToday) {
                                        Box(modifier = Modifier.size(4.dp).clip(CircleShape).background(if (isLogged) Color.White else TodayColor))
                                    }
                                    if (isSexual) {
                                        val icon = when (sexualType) {
                                            "protected" -> Icons.Default.CheckCircle
                                            "masturbation" -> Icons.Default.Person
                                            else -> Icons.Default.Favorite
                                        }
                                        val iconTint = when (sexualType) {
                                            "protected" -> Color(0xFF81C784)
                                            "masturbation" -> Color(0xFF64B5F6)
                                            else -> Color(0xFFE57373)
                                        }
                                        Icon(
                                            imageVector = icon, 
                                            contentDescription = null, 
                                            tint = if (isLogged) Color.White else iconTint, 
                                            modifier = Modifier.size(8.dp)
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
                // Fill remaining empty slots in the last row to maintain alignment
                repeat(7 - rowDays.size) {
                    Spacer(modifier = Modifier.weight(1f).height(44.dp))
                }
            }
        }
    }
}

@Composable
fun CalendarScreen(
    cycleTracker: CycleTracker, 
    entries: List<CycleEntry>,
    isPartner: Boolean = false,
    partnerPerms: PartnerPermissions? = null,
    onEditEntry: (CycleEntry) -> Unit,
    onDeleteEntry: (Long) -> Unit
) {
    val coroutineScope = rememberCoroutineScope()
    val initialPage = 500
    val pagerState = androidx.compose.foundation.pager.rememberPagerState(
        initialPage = initialPage,
        pageCount = { 1000 }
    )

    val currentMonth = remember(pagerState.currentPage) {
        val offset = pagerState.currentPage - initialPage
        val now = UiYearMonth.now()
        var newYear = now.year + offset / 12
        var newMonth = now.monthNumber + offset % 12
        
        if (newMonth > 12) {
            newYear += newMonth / 12
            newMonth %= 12
        } else if (newMonth < 1) {
            newYear += (newMonth - 12) / 12
            newMonth = 12 + (newMonth % 12)
            if (newMonth == 12) {
                newYear -= 1
            }
        }
        UiYearMonth(newYear, newMonth)
    }

    // CRITICAL: collectAsState() forces Compose to redraw the grid when the ViewModel pushes new arrays
    val loggedDates by cycleTracker.loggedDates.collectAsState()
    val predictedDates by cycleTracker.predictedDates.collectAsState()
    val fertileDates by cycleTracker.fertileDates.collectAsState()
    
    var selectedDate by remember { mutableStateOf<LocalDate?>(null) }

    Column(modifier = Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)) {
        CalendarHeader(
            currentMonth = currentMonth,
            onPrevMonth = {
                coroutineScope.launch {
                    pagerState.animateScrollToPage(pagerState.currentPage - 1)
                }
            },
            onNextMonth = {
                coroutineScope.launch {
                    pagerState.animateScrollToPage(pagerState.currentPage + 1)
                }
            }
        )
        
        // Weekdays Header
        Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 8.dp)) {
            val weekDays = listOf("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
            weekDays.forEach { day ->
                Text(
                    text = day,
                    modifier = Modifier.weight(1f),
                    textAlign = TextAlign.Center,
                    style = MaterialTheme.typography.bodySmall.copy(fontWeight = FontWeight.Bold),
                    color = Color.Gray
                )
            }
        }

        val sexualActivityDates = remember(entries, isPartner, partnerPerms) {
            if (isPartner && (partnerPerms?.shareSexualActivity != true)) {
                emptyMap()
            } else {
                entries.mapNotNull { entry -> entry.sexualRelations?.let { LocalDate.parse(entry.date) to it } }.toMap()
            }
        }

        androidx.compose.foundation.pager.HorizontalPager(
            state = pagerState,
            modifier = Modifier.fillMaxWidth().wrapContentHeight()
        ) { page ->
            val offset = page - initialPage
            val now = UiYearMonth.now()
            var newYear = now.year + offset / 12
            var newMonth = now.monthNumber + offset % 12
            
            if (newMonth > 12) {
                newYear += newMonth / 12
                newMonth %= 12
            } else if (newMonth < 1) {
                newYear += (newMonth - 12) / 12
                newMonth = 12 + (newMonth % 12)
                if (newMonth == 12) {
                    newYear -= 1
                }
            }
            val pageMonth = UiYearMonth(newYear, newMonth)

            val filteredLoggedDates = if (isPartner && (partnerPerms?.shareFlowIntensity != true)) emptySet() else loggedDates
            val filteredPredictedDates = if (isPartner && (partnerPerms?.shareCyclePhase != true)) emptySet() else predictedDates
            val filteredFertileDates = if (isPartner && (partnerPerms?.shareCyclePhase != true)) emptySet() else fertileDates

            CalendarGrid(
                currentMonth = pageMonth,
                loggedDates = filteredLoggedDates,
                predictedDates = filteredPredictedDates,
                fertileDates = filteredFertileDates,
                sexualActivityDates = sexualActivityDates,
                selectedDate = selectedDate,
                onDateSelected = { 
                    if (selectedDate == it) selectedDate = null else selectedDate = it 
                }
            )
        }

        // ADD THIS LINE RIGHT AFTER THE GRID
        CalendarLegend()
        
        Spacer(modifier = Modifier.height(16.dp))
        
        Row(
            modifier = Modifier.fillMaxWidth().padding(16.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = selectedDate?.let { "Logs for ${it.toHumanReadable()}" } ?: "History",
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold)
            )
            if (selectedDate != null) {
                TextButton(onClick = { selectedDate = null }) {
                    Text("Clear Filter")
                }
            }
        }
        
        LazyColumn(
            modifier = Modifier.fillMaxWidth().weight(1f),
            contentPadding = PaddingValues(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            if (selectedDate != null) {
                val displayEntries = entries.filter { it.date == selectedDate.toString() }
                items(displayEntries) { entry ->
                    HistoryItem(
                        entry = entry,
                        isPartner = isPartner,
                        partnerPerms = partnerPerms,
                        onEdit = { onEditEntry(entry) },
                        onDelete = { entry.id?.let { onDeleteEntry(it) } }
                    )
                }
                if (displayEntries.isEmpty()) {
                    item {
                        Text("No logs for this date.", color = Color.Gray, modifier = Modifier.padding(16.dp))
                    }
                }
                
                if (!isPartner) {
                    item {
                        val currentEntry = displayEntries.firstOrNull()
                        val currentRel = currentEntry?.sexualRelations

                    Column(modifier = Modifier.fillMaxWidth().padding(top = 16.dp)) {
                        Text("Log Sexual Activity", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        Spacer(Modifier.height(8.dp))
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceEvenly
                        ) {
                            listOf("Protected", "Unprotected", "Masturbation").forEach { rel ->
                                FilterChip(
                                    selected = currentRel == rel,
                                    onClick = { 
                                        val newRel = if (currentRel == rel) null else rel
                                        selectedDate?.let { cycleTracker.logSexualRelation(it, newRel) }
                                    },
                                    label = { Text(rel) }
                                )
                            }
                        }
                    }
                }
                } // End of if (!isPartner)
            } else {
                val groups = groupPeriodEntries(entries)
                items(groups) { group ->
                    HistoryGroupItem(
                        group = group,
                        isPartner = isPartner,
                        partnerPerms = partnerPerms,
                        onDelete = {
                            group.ids.forEach { id -> onDeleteEntry(id) }
                        }
                    )
                }
                if (groups.isEmpty()) {
                    item {
                        Text("No period logs found.", color = Color.Gray, modifier = Modifier.padding(16.dp))
                    }
                }
            }
        }
    }
}

data class PeriodGroup(
    val startDate: kotlinx.datetime.LocalDate,
    val endDate: kotlinx.datetime.LocalDate,
    val maxIntensity: Int,
    val notes: String,
    val ids: List<Long>,
    val maxPainLevel: Int? = null,
    val symptoms: Set<String> = emptySet()
)

fun groupPeriodEntries(entries: List<CycleEntry>): List<PeriodGroup> {
    val sorted = entries.filter { (it.intensity ?: 0) > 0 }
        .map { Pair(kotlinx.datetime.LocalDate.parse(it.date), it) }
        .sortedBy { it.first }
    
    if (sorted.isEmpty()) return emptyList()
    
    val groups = mutableListOf<PeriodGroup>()
    var currentStart = sorted[0].first
    var currentEnd = sorted[0].first
    var maxInt = sorted[0].second.intensity?.toInt() ?: 0
    var combinedNotes = sorted[0].second.notes ?: ""
    var currentIds = mutableListOf<Long>()
    sorted[0].second.id?.let { currentIds.add(it) }
    var maxPain = sorted[0].second.painLevel?.toInt()
    var combinedSymptoms = sorted[0].second.symptoms?.split(",")?.map { it.trim() }?.filter { it.isNotEmpty() }?.toMutableSet() ?: mutableSetOf()
    
    for (i in 1 until sorted.size) {
        val (date, entry) = sorted[i]
        val prevDate = sorted[i-1].first
        
        if (date.toEpochDays() - prevDate.toEpochDays() <= 15L) {
            currentEnd = date
            val int = entry.intensity?.toInt() ?: 0
            if (int > maxInt) maxInt = int
            val pain = entry.painLevel?.toInt()
            if (pain != null && (maxPain == null || pain > maxPain)) maxPain = pain
            entry.symptoms?.split(",")?.map { it.trim() }?.filter { it.isNotEmpty() }?.let { combinedSymptoms.addAll(it) }
            if (!entry.notes.isNullOrBlank()) {
                if (!combinedNotes.contains(entry.notes)) {
                    combinedNotes += if (combinedNotes.isBlank()) entry.notes else " | ${entry.notes}"
                }
            }
            entry.id?.let { currentIds.add(it) }
        } else {
            groups.add(PeriodGroup(currentStart, currentEnd, maxInt, combinedNotes, currentIds, maxPain, combinedSymptoms))
            currentStart = date
            currentEnd = date
            maxInt = entry.intensity?.toInt() ?: 0
            combinedNotes = entry.notes ?: ""
            currentIds = mutableListOf()
            entry.id?.let { currentIds.add(it) }
            maxPain = entry.painLevel?.toInt()
            combinedSymptoms = entry.symptoms?.split(",")?.map { it.trim() }?.filter { it.isNotEmpty() }?.toMutableSet() ?: mutableSetOf()
        }
    }
    groups.add(PeriodGroup(currentStart, currentEnd, maxInt, combinedNotes, currentIds, maxPain, combinedSymptoms))
    return groups.reversed()
}

@Composable
fun HistoryGroupItem(group: PeriodGroup, isPartner: Boolean = false, partnerPerms: PartnerPermissions? = null, onDelete: () -> Unit) {
    val periodColor = LocalAppColors.current.primary
    val showIntensity = !isPartner || (partnerPerms?.shareFlowIntensity == true)
    val showNotes = !isPartner || (partnerPerms?.shareSymptomsMoods == true)
    
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Row(
            modifier = Modifier.padding(16.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Box(
                modifier = Modifier
                    .size(12.dp)
                    .clip(RoundedCornerShape(2.dp))
                    .background(periodColor)
            )
            
            Spacer(Modifier.width(16.dp))
            
            Column(modifier = Modifier.weight(1f)) {
                val dateStr = if (group.startDate == group.endDate) {
                    group.startDate.toHumanReadable()
                } else {
                    "${group.startDate.toHumanReadable()} - ${group.endDate.toHumanReadable()}"
                }
                Text(dateStr, style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold))
                
                val intensityPart = if (showIntensity) "Intensity: ${group.maxIntensity}" else "Period Logged"
                val painPart = if (showNotes && group.maxPainLevel != null) " | Pain: ${group.maxPainLevel}/10" else ""
                val sympPart = if (showNotes && group.symptoms.isNotEmpty()) "\nSymptoms: ${group.symptoms.joinToString(", ")}" else ""
                val notesPart = if (showNotes && group.notes.isNotBlank()) "\n${group.notes}" else ""
                val fullNotes = "$intensityPart$painPart$sympPart$notesPart"
                Text(fullNotes, style = MaterialTheme.typography.bodySmall, color = Color.Gray)
            }
            
            if (!isPartner) {
                IconButton(onClick = onDelete) {
                    Icon(Icons.Default.Delete, contentDescription = "Delete", tint = Color.LightGray)
                }
            }
        }
    }
}

@Composable
fun HistoryItem(entry: CycleEntry, isPartner: Boolean = false, partnerPerms: PartnerPermissions? = null, onEdit: () -> Unit, onDelete: () -> Unit) {
    val periodColor = LocalAppColors.current.primary
    val showIntensity = !isPartner || (partnerPerms?.shareFlowIntensity == true)
    val showNotes = !isPartner || (partnerPerms?.shareSymptomsMoods == true)
    val showSexual = !isPartner || (partnerPerms?.shareSexualActivity == true)
    
    val isPeriodLog = (entry.intensity ?: 0) > 0
    val hasSexualActivity = !entry.sexualRelations.isNullOrBlank()
    Card(
        modifier = Modifier.fillMaxWidth().then(
            if (!isPartner && isPeriodLog && !hasSexualActivity) Modifier.clickable { onEdit() } else Modifier
        ),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Row(
            modifier = Modifier.padding(16.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Box(
                modifier = Modifier
                    .size(12.dp)
                    .clip(RoundedCornerShape(2.dp))
                    .background(periodColor)
            )
            
            Spacer(Modifier.width(16.dp))
            
            Column(modifier = Modifier.weight(1f)) {
                Text(kotlinx.datetime.LocalDate.parse(entry.date).toHumanReadable(), style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold))
                
                val notesStr = if (showNotes) (entry.notes ?: "") else ""
                val sympStr = if (showNotes && !entry.symptoms.isNullOrBlank()) "Symptoms: ${entry.symptoms?.replace(",", ", ")}" else ""
                val rel = if (showSexual) entry.sexualRelations else null
                val intensityPart = if (showIntensity && (entry.intensity ?: 0) > 0) "Intensity: ${entry.intensity}" else ""
                val painPart = if (showNotes && (entry.painLevel ?: 0) > 0) "Pain: ${entry.painLevel}/10" else ""
                val relPart = if (!rel.isNullOrBlank()) "Activity: ${rel.replaceFirstChar { it.uppercase() }}" else ""
                
                val topRow = listOf(intensityPart, painPart, relPart).filter { it.isNotBlank() }.joinToString(" | ")
                val midRow = if (sympStr.isNotBlank()) sympStr else ""
                val fullNotes = listOf(topRow, midRow, notesStr).filter { it.isNotBlank() }.joinToString("\n")
                
                Text(if (fullNotes.isBlank()) "No details" else fullNotes, style = MaterialTheme.typography.bodySmall, color = Color.Gray)
            }

            if (!isPartner) {
                IconButton(onClick = onDelete) {
                    Icon(
                        Icons.Default.Delete, 
                        contentDescription = "Delete entry", 
                        tint = Color.Gray.copy(alpha = 0.5f),
                        modifier = Modifier.size(20.dp)
                    )
                }
            }
        }
    }
}

@Composable
fun CalendarLegend() {
    val appColors = LocalAppColors.current
    val PeriodColor = appColors.primaryVariant
    val FertileColor = appColors.secondaryVariant

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 16.dp),
        horizontalArrangement = Arrangement.Center,
        verticalAlignment = Alignment.CenterVertically
    ) {
        // 1. Period Indicator
        LegendItem(
            text = "Period",
            iconModifier = Modifier.background(PeriodColor, CircleShape)
        )

        Spacer(modifier = Modifier.width(24.dp))

        // 2. Predicted Indicator (Dotted)
        LegendItem(
            text = "Predicted",
            iconModifier = Modifier.drawBehind {
                drawCircle(
                    color = PeriodColor,
                    style = Stroke(
                        width = 1.5.dp.toPx(),
                        pathEffect = PathEffect.dashPathEffect(
                            intervals = floatArrayOf(6f, 6f),
                            phase = 0f
                        )
                    )
                )
            }
        )

        Spacer(modifier = Modifier.width(24.dp))

        // 3. Fertile Indicator
        LegendItem(
            text = "Fertile",
            iconModifier = Modifier.background(FertileColor, CircleShape)
        )

        Spacer(modifier = Modifier.width(24.dp))

        // 4. Today Indicator
        LegendItem(
            text = "Today",
            iconModifier = Modifier.background(LocalAppColors.current.todayHighlight, CircleShape).padding(4.dp)
        )
    }
}

@Composable
private fun LegendItem(text: String, iconModifier: Modifier) {
    Row(verticalAlignment = Alignment.CenterVertically) {
        Box(
            modifier = Modifier
                .size(14.dp)
                .then(iconModifier)
        )
        Spacer(modifier = Modifier.width(8.dp))
        Text(
            text = text,
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
    }
}
